os: Visual Studio 2017
version: v1.10.2.build{build}

install:
  - cinst -y nsis

matrix:
  fast_finish: true
  allow_failures:
    - platform: x86
      configuration: Release
    - platform: x64
      configuration: Release

platform:
  - x86
  - x64

configuration:
  - Release

build_script:
  # Fixed tag version number if using a tag.
  - cmd: if "%APPVEYOR_REPO_TAG%" == "true" set APPVEYOR_BUILD_VERSION=%APPVEYOR_REPO_TAG_NAME%
  # vcbuild overwrites the platform variable.
  - cmd: |
        set ARCH=%platform%
        "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat"
        set GYP_MSVS_VERSION=2015
        vcbuild.bat nobuild
  - ps: .\appveyor.ps1
  - cmd: vcbuild.bat release %ARCH% shared noprojgen

# after_build:
#   - '"%PROGRAMFILES(x86)%\NSIS\makensis" /DVERSION=%APPVEYOR_BUILD_VERSION% /DARCH=%ARCH% libuv.nsi'

artifacts:
  - name: Installer
    path: 'libuv-*.exe'

cache:
  - C:\projects\libuv\build\gyp
